version: '3'
services: 
  go:
    build: 
      context: .
    volumes:
      - ./src:/go/src
    ports: 
      - 8080:8080
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev
    ports:
      - 3307:3306